#!/bin/bash

# SCC Algorithm Test Script - Simplified Version
# Tests the SCC implementation with cyclic dependencies

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         SCC Algorithm Functionality Test                       ║"
echo "║  Testing with Test JAR containing deliberate cycles           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

PROJECT_DIR=".."
TEST_JAR="$PROJECT_DIR/test-jar/target/test-cyclic-dependencies-1.0.0.jar"

echo "📦 Test JAR Information:"
echo "   Path: $TEST_JAR"
echo ""

if [ ! -f "$TEST_JAR" ]; then
    echo "❌ ERROR: Test JAR not found"
    exit 1
fi

# Show expected structure
echo "═══════════════════════════════════════════════════════════════════"
echo "📊 EXPECTED DEPENDENCY STRUCTURE"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "┌─ TANGLE 1: Two-Node Cycle ────────────────────────────────────┐"
echo "│                                                                │"
echo "│  ┌──────────────────────────────┐                             │"
echo "│  │  com.example.a               │                             │"
echo "│  │  (imports com.example.b)     │                             │"
echo "│  └────────────┬─────────────────┘                             │"
echo "│               │                                                │"
echo "│               ▼                                                │"
echo "│  ┌──────────────────────────────┐                             │"
echo "│  │  com.example.b               │                             │"
echo "│  │  (imports com.example.a)     │ ◄─── CYCLE!                 │"
echo "│  │  (imports com.example.c)     │ ◄─── VIOLATION (upward)     │"
echo "│  └──────────────────────────────┘                             │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

echo "┌─ TANGLE 2: Three-Node Cycle ──────────────────────────────────┐"
echo "│                                                                │"
echo "│  ┌──────────────────────────────┐                             │"
echo "│  │  com.example.c               │                             │"
echo "│  │  (imports com.example.d)     │                             │"
echo "│  └────────────┬─────────────────┘                             │"
echo "│               │                                                │"
echo "│               ▼                                                │"
echo "│  ┌──────────────────────────────┐                             │"
echo "│  │  com.example.d               │                             │"
echo "│  │  (imports com.example.e)     │                             │"
echo "│  └────────────┬─────────────────┘                             │"
echo "│               │                                                │"
echo "│               ▼                                                │"
echo "│  ┌──────────────────────────────┐                             │"
echo "│  │  com.example.e               │                             │"
echo "│  │  (imports com.example.c)     │ ◄─── CYCLE!                 │"
echo "│  └──────────────────────────────┘                             │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "📋 EXPECTED ANALYSIS RESULTS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✓ SCCs Found: 2 (plus 0 single nodes)"
echo ""
echo "  🔴 TANGLE #0:"
echo "     Members: [com.example.a, com.example.b]"
echo "     Size: 2"
echo "     Level: 1"
echo "     Type: 2-node cycle"
echo ""
echo "  🔴 TANGLE #1:"
echo "     Members: [com.example.c, com.example.d, com.example.e]"
echo "     Size: 3"
echo "     Level: 0 (leaf)"
echo "     Type: 3-node cycle"
echo ""
echo "⚠️  VIOLATIONS (upward edges): 1"
echo "     • com.example.b → com.example.c ❌"
echo ""
echo "✓ NORMAL edges (downward): 0"
echo ""
echo "🔗 INTRA-SCC edges: 5"
echo "     • a → b, b → a (2 in TANGLE #0)"
echo "     • c → d, d → e, e → c (3 in TANGLE #1)"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🧪 RUNNING ACTUAL ANALYSIS..."
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Run with AnalyzerExample which already uses LayerAssigner
cd "$PROJECT_DIR"
java -cp "target/classes:$TEST_JAR" de.weigend.s202.example.AnalyzerExample "$TEST_JAR" 2>&1 | \
  head -100

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Test complete! Check the output above for SCC analysis results."
echo ""
echo "🎯 What to look for:"
echo "   1. SCCs Found section should show 2 SCCs"
echo "   2. Both SCCs should be marked as TANGLE (size > 1)"
echo "   3. Level assignment: TANGLE #1 should be Level 0, TANGLE #0 should be Level 1"
echo "   4. Violation: b → c should appear in output"
echo ""
